export interface IAppHost {
    /**
     * Queries the host application for the name of the app.
     *
     * @returns The name of the client.
     */
    appName(): string;

    /**
     * Queries the host application for a the version of the app.
     *
     * @returns The version of the app.
     */
    appVersion(): string;

    /**
     * Queries the host application for a unique Device ID.
     *
     * @returns The unique ID of the device.
     */
    deviceID(): string;

    /**
     * Queries the host application for a display name from the device.
     *
     * @returns The display name of the device.
     */
    deviceName(): string;

    /**
     * Dispatches exit procedures to the host application.
     *
     * _Currently only supported on Tizen._
     */
    exit(): void;

    /**
     * Queries the host application for the default layout to use in the client.
     *
     * @returns A string containing the identifier of the layout to use.
     */
    getDefaultLayout(): "mobile" | "desktop" | "tv";

    /**
     *  Queries the host application for a profile of media that are natively supported by the app.
     *
     * @param profile A Profile object generated by the web client and describing the media capabilities of the client.
     * @returns A Profile object describing the full capabilities of the client.
     */
    getDeviceProfile(profile: IProfile): IProfile;

    /**
     * Dispatches initialization procedures to the host application.
     *
     * @returns Object containing the capabilities of the client. _Seems to be unused._
     */
    init(): IAppInfo;

    /**
     * Queries the host application for support of a feature.
     *
     * _For supported commands check: {@link Command}_
     *
     * @param command command that should be checked
     */
    supports(command: Command): boolean;
}

/**
 * Command available
 *
 * See also: {@link IAppHost.supports}
 */
export enum Command {
    /**
     * TODO: Add info
     */
    CAST_MENU_HASH_CHANGE = "castmenuhashchange",
    /**
     * TODO: Add info
     */
    CHROMECAST = "chromecast",
    /**
     * TODO: Add info
     */
    DISPLAY_LANGUAGE = "displaylanguage",
    /**
     * TODO: Add info
     */
    DISPLAY_MODE = "displaymode",
    /**
     * TODO: Add info
     */
    EXIT = "exit",
    /**
     * TODO: Add info
     */
    EXTERNAL_LINKS = "externallinks",
    /**
     * TODO: Add info
     */
    EXTERNAL_PLAYER_INTENT = "externalplayerintent",
    /**
     * TODO: Add info
     */
    FILE_DOWNLOAD = "filedownload",
    /**
     * TODO: Add info
     */
    FILE_INPUT = "fileinput",
    /**
     * TODO: Add info
     */
    FULLSCREEN_CHANGE = "fullscreenchange",
    /**
     * TODO: Add info
     */
    HTML_VIDEO_AUTOPLAY = "htmlvideoautoplay",
    /**
     * TODO: Add info
     */
    IMAGE_ANALYSIS = "imageanalysis",
    /**
     * TODO: Add info
     */
    MULTI_SERVER = "multiserver",
    /**
     * TODO: Add info
     */
    PHYSICAL_VOLUME_CONTROL = "physicalvolumecontrol",
    /**
     * TODO: Add info
     */
    REMOTE_AUDIO = "remoteaudio",
    /**
     * TODO: Add info
     */
    REMOTE_CONTROL = "remotecontrol",
    /**
     * TODO: Add info
     */
    REMOTE_VIDEO = "remotevideo",
    /**
     * TODO: Add info
     */
    RUN_AT_STARTUP = "runatstartup",
    /**
     * TODO: Add info
     */
    SCREENSAVER = "screensaver",
    /**
     * TODO: Add info
     */
    SHARING = "sharing",
    /**
     * TODO: Add info
     */
    SKINS = "skins",
    /**
     * TODO: Add info
     */
    SOUNDEFFECTS = "soundeffects",
    /**
     * TODO: Add info
     */
    SUBTITLE_APPEARANCE_SETTINGS = "subtitleappearancesettings",
    /**
     * TODO: Add info
     */
    SUBTITLE_BURN_SETTINGS = "subtitleburnsettings",
    /**
     * TODO: Add info
     */
    SYNC = "sync",
    /**
     * TODO: Add info
     */
    TARGET_BLANK = "targetblank",
}

/**
 * Basic info about the app
 *
 * See also: {@link IAppHost.init}
 */
export interface IAppInfo {
    /**
     * A unique and persistent device identifier
     */
    deviceId: string;
    /**
     * A display name from the device
     *
     * _Example: My Phone_
     */
    deviceName: string;
    /**
     * The display name for the app
     *
     * _Example: Jellyfin for Platform X_
     */
    appName: string;
    /**
     * The version of the App
     *
     * _Example: 1.0.0_
     */
    appVersion: string;
}

export interface IDirectPlayProfile {
    Container: string;
    Type: string;
    VideoCodec: string;
    AudioCodec: string;
}

export interface ICodecProfileCondition {
    Condition: string;
    Property: string;
    Value: string;
    IsRequired: boolean;
}

export interface ICodecProfile {
    Type: string;
    Codec: string;
    Conditions: ICodecProfileCondition[];
}

export interface ISubtitleProfile {
    Format: string;
    Method: string;
}

export interface IResponseProfile {
    Type: string;
    Container: string;
    MimeType: string;
}

export interface IProfile {
    MaxStreamingBitrate: number;
    MaxStaticBitrate: number;
    MaxStaticMusicBitrate: number;
    MusicStreamingTranscodingBitrate: number;
    DirectPlayProfiles: IDirectPlayProfile[];
    CodecProfiles: ICodecProfile[];
    SubtitleProfiles: ISubtitleProfile[];
    ResponseProfiles: IResponseProfile[];
}
